### ISSUE TITLE
Please provide data format document

### ISSUE THREAD

**Issue by jasperdnar** [vletoux/GidsApplet#29]
Please provide how data is formatted in GIDS applet by this i mean...

1. Which comression technique is used in certificate 
2. What are different Tags 
3. Why opensc is choosing File id as A000, A010... and how we decide what should be the value in it?

if there is any documentation let me know.

**Comment by martinpaljak** [comment]
Please read the only documentation available https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn642100(v=vs.85)?redirectedfrom=MSDN

**Comment by vletoux** [comment]
I've made the Opensc implementation based on the specification.
There is a missing part that can be found in the minidriver specification (card initialization)

**Comment by jasperdnar** [comment]
Thanks got it.
