### ISSUE TITLE
How do the tests work

### ISSUE THREAD

**Issue by cheburashka** [vletoux/GidsApplet#4]
Hi Vletoux, I wonder if you could give me some details about how to run the unit tests, do they use a proprietary card emulator or the reference implementation from Oracle? If you could describe a bit the setup that would be great, or start a wiki page for that and I'm happy to contribute to it.

**Comment by vletoux** [comment]
It is using com.licel.jcardsim as a card simulator into junit tests (https://jcardsim.org/)
Just add a reference to the simulator.

Then the APDU comes from a capture made with the Windows minidriver.
